services:
  - type: web
    name: shynliairbnbcleaning
    runtime: static
    branch: main
    autoDeployTrigger: commit
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
